name: CI

on:
  push:
    branches:
      - main

jobs:
  latex-build:
    name: "PDF Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        design: [homepage-patch, homepage+subtitle]
    steps:
      - uses: actions/checkout@v2
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic --keep-logs  ${{ matrix.design }}/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.design }}
          if-no-files-found: error
          path: |
            ${{ matrix.design }}/main.pdf
            ${{ matrix.design }}/main.log
