name: CI

on:
  push:
    branches:
      - main

jobs:
  latex-build:
    name: "PDF Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tectonic
        run: tectonic --keep-logs  homepage/main.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: homepage
          if-no-files-found: error
          path: |
            homepage/main.pdf
            homepage/main.log
